### ISSUE TITLE
Is this a functioning HA addon?

### ISSUE THREAD

**Issue by tbgoose** [DasLetzteEinhorn/AlphaESS_Monitor_Hass#1]
Hey

Does this work? What are the install steps to get it working?

**Comment by DasLetzteEinhorn** [comment]
The plugin is just a web scraper based on Selenium. It is very resource intensive and does not work very reliably.
Since AlphaEss has announced an API (probably Modbus-TPC), I think this plugin is not very useful, because it breaks from time to time when the website is updated.

If you still want to test it:

Add `https://github.com/DasLetzteEinhorn/AlphaESS_Monitor_Hass` as a repo and install the addon.
My example settings:

```
log_level: debug
base_topic: alphaess
timeout: 10
username: '!secret alpha_user'
password: '!secret alpha_pass'
mqtt_username: '!secret mqtt_user'
mqtt_password: '!secret mqtt_pass'
mqtt_host: 192.168.42.113
```

If you run the plugin on the same instance as the MQTT broker, the last three lines can be omitted.

To get the sensors working, I use the following (on my main instance):

```
sensor:
  - platform: mqtt
    name: "Solar Battery"
    state_topic: "alphaess/battery"
    unit_of_measurement: '%'
    icon: mdi:battery
  - platform: mqtt
    name: "Solar Generation"
    state_topic: "alphaess/pv"
    unit_of_measurement: 'kW'
    icon: mdi:solar-panel-large
  - platform: mqtt
    name: "Solar Feed In"
    state_topic: "alphaess/feed_in"
    unit_of_measurement: 'kW'
    icon: mdi:transmission-tower
  - platform: mqtt
    name: "Solar Grid Consumption"
    state_topic: "alphaess/grid_consumption"
    unit_of_measurement: 'kW'
    icon: mdi:transmission-tower
  - platform: mqtt
    name: "Solar Load"
    state_topic: "alphaess/load"
    unit_of_measurement: 'kW'
    icon: mdi:power-socket-de
    
```
