### ISSUE TITLE
Detail on what the data means.

### ISSUE THREAD

**Issue by nmthas** [DasLetzteEinhorn/AlphaESS_Monitor_Hass#6]
Hi and thanks for your work so far.  I am using this addon to communicate with my Alpha-ESS battery system.  I am trying to understand what each of the data items mean.  Do you have a description of each item?

I would like to use something like custom:power-distribution-card (https://github.com/JonahKr/power-distribution-card) to display the values in Home Assistant.  FYI I have attached a copy of the logfile.

Something like the following is what I am after (with real numbers):
![image](https://user-images.githubusercontent.com/39108642/137647160-0a5c7924-ed55-4d0e-95a3-6baf22142beb.png
[alpha-ess.log](https://github.com/DasLetzteEinhorn/AlphaESS_Monitor_Hass/files/7360979/alpha-ess.log)
)

**Comment by nmthas** [comment]
Hey Thanks for responding,

If you have all of those values, isn't the current load just the
combination thereof.

i.e.  Solar Watts Being Generated +or- Grid I/O (depending on flow
direction) +or- Battery I/O (depending on flow)

I also guess that your calculations for the sensors (eg  Solar
Generation + solar_grid_i_o_total
+ Solar Battery I/O)will probably even just enable you to add them all
together (because if energy is flowing out it will be a negative value
anyway)

I have some issues with the data I'm receiving which I am still trying to
rectify (for example I'm not getting a real value for input from the grid,
at this stage I think it is an install/configuration issue.  I am trying to
get the installer to fix at the moment, I will have a look at this in more
detail when I'm receiving a full data set from my battery.

Regards,

Nick
_____________________________________________________________________________

Nick Mathas
+61 408 464 143
***@***.***

**Comment by Spookster** [comment]
After watching the data for a while, pbat seems to report 0 more often than not when the battery is at 100%
However the web interface shows power going in or out (as solar production drops) , the reporting doesnt seem to be accurate enough to calculate load?
Load would be a good figure to have available, but how?

**Comment by Spookster** [comment]
To be fair, it works well with the code below:

```
  - platform: template
    sensors:
      solar_load_total:
        friendly_name: "Solar Load Total"
        unit_of_measurement: 'W'
        value_template: "{{ states('sensor.solar_grid_i_o_l1') | float + states('sensor.solar_battery_i_o') | float + states('sensor.solar_gen_ppv1') | float + states('sensor.solar_gen_ppv2') | float}}"
```
The values seem consistent with the interface.
Using a custom card - power-distribution-card

![Untitled](https://user-images.githubusercontent.com/982535/148156055-803e6556-8c65-4b0a-9b00-9e4cae69370d.png)
